### ISSUE TITLE
Sentence mistake

### ISSUE THREAD

**Issue by AksharPrajapati** [redsoftware-hq/docs.github.io#10]
![image (1)](https://user-images.githubusercontent.com/46050915/148724585-495af60f-405a-4e88-9bb3-5e53c2d92117.png)

**Comment by 3sanket3** [comment]
How about if you can submit the PR. [Here](https://redsoftware-hq.github.io/docs.github.io/how-to-contribute.html) are the steps 🙂

**Comment by 3sanket3** [comment]
Resolved via https://github.com/redsoftware-hq/docs.github.io/commit/802856d799cf1b281aa9c512cfaf2a5b2fd77c6f
